name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
    - "GitOps"
    - ".github/workflows/gitops.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file GitOps/Dockerfile --tag rodrigodeco/gitops:v1-$GITHUB_RUN_ID
      
    - name: Push to registry
      run: docker push rodrigodeco/gitops:v1-$GITHUB_RUN_ID

