name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
    - "GitOps/**"
    - ".github/workflows/gitops.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file GitOps/Dockerfile --tag rodrigodeco/gitops:v1-$GITHUB_RUN_NUMBER
  
    - name: Login DockerHub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
      
    - name: Push to registry
      run: docker push rodrigodeco/gitops:v1-$GITHUB_RUN_NUMBER

    - name: Build the Docker image
      run: docker build . --file GitOps/Dockerfile --tag rodrigodeco/gitops:v1-$GITHUB_RUN_NUMBER
    
    - name: Logout DockerHub
      run: docker logout  
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Update Image Tag Values
      run: |
        cat GitOps/manifests/deployment.yaml | grep v1
        sed -i "s/v1-[^ ]*/v1-$GITHUB_RUN_NUMBER/" GitOps/manifests/deployment.yaml
        cat GitOps/manifests/deployment.yaml | grep v1
        
    - name: Commit the changes made
      run: | 
        git config --global user.name 'Rodrigo Deco'
        git config --global user.email 'ro.deco@hotmail.es'
        git add GitOps/manifests/deployment.yaml
        git commit -am "updating image tag"
        git push https://${{ secrets.GIT_TOKEN }}@github.com/RodrigoDeco/devops.git HEAD:master
