name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
    - "GitOps/"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gitops:v1-$(date +%s)
      
    - name: Push to registry
      run: docker push rodrigodeco/gitops:v1-$(date +%s)

