name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
    - "GitOps/**"
    - ".github/workflows/gitops.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file GitOps/Dockerfile --tag rodrigodeco/gitops:v1-$GITHUB_RUN_ID
  
    - name: Login DockerHub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
      
    - name: Push to registry
      run: docker push rodrigodeco/gitops:v1-$GITHUB_RUN_ID

    - name: Build the Docker image
      run: docker build . --file GitOps/Dockerfile --tag rodrigodeco/gitops:v1-$GITHUB_RUN_ID
    
    - name: Logout DockerHub
      run: docker logout  
  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Update Image Tag Values
      run: |
        export chart_dir="GitOps/manifests"
        
        # Update the values.yaml file with the new image tag
        sed -i "s/^  gitops:v1-.*/  gitops:v1-$GITHUB_RUN_ID" "$chart_dir/deployment.yaml"
    
    - name: Commit the changes made
      run: | 
        git config --global user.name 'Rodrigo Deco'
        git config --global user.email 'ro.deco@hotmail.es'
        git commit -am "updating image tag"
        git push
